version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
  - dependency-name: eslint-plugin-unicorn
    versions:
    - 27.0.0
  registries:
  - npm-registry-npm-pkg-github-com
